# Generated by Django 3.0.6 on 2020-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200516_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(upload_to='products/', verbose_name='Главное фото'),
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
