# Generated by Django 3.0.6 on 2020-05-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200517_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Дополнительная фотография', 'verbose_name_plural': 'Дополнительные фотографии'},
        ),
    ]
